'use client';
import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { api } from '@/lib/api';
type Item={id:number;title?:string;content?:string};
type Quiz={question?:string;options?:Array<string|{text:string}>;answer?:number;correct_index?:number;explanation?:string;topic?:string};
const tabs=['全部','Python基础','NumPy','Pandas','数据清洗','可视化'];
function parse(item:Item):Quiz{try{const v=JSON.parse(item.content||'{}');if(v?.question)return v;}catch{}return{question:(item.title||'未命名错题').replace(/^错题[:：]?\s*/,''),options:[],answer:0,explanation:item.content||'请回顾相关知识点。'};}
function category(item:Item,q:Quiz){const t=`${q.question||''}${q.topic||''}${item.title||''}`.toLowerCase();if(/numpy|ndarray|数组|广播/.test(t))return'NumPy';if(/pandas|dataframe|series|groupby/.test(t))return'Pandas';if(/清洗|缺失|异常|重复/.test(t))return'数据清洗';if(/可视化|matplotlib|seaborn|图表/.test(t))return'可视化';return'Python基础';}
export default function WrongQuestionBook(){const router=useRouter();const[items,setItems]=useState<Item[]>([]);const[tab,setTab]=useState('全部');const[active,setActive]=useState<Item|null>(null);const[selected,setSelected]=useState<number|null>(null);const[submitted,setSubmitted]=useState(false);useEffect(()=>{const load=()=>api.getNotes({category:'wrong_question'}).then(d=>setItems(d||[])).catch(()=>{});load();const id=window.setInterval(load,5000);return()=>window.clearInterval(id)},[]);const list=useMemo(()=>tab==='全部'?items:items.filter(i=>category(i,parse(i))===tab),[items,tab]);const addReview=async(item:Item)=>{const today=new Date().toISOString().slice(0,10);await api.addDailyTask({date:today,content:`复习错题：${parse(item).question}`,category:'review'}).catch(()=>{});};return <main className="min-h-full rounded-2xl bg-[#effcfc] p-6 text-[#38515a] lg:p-8"><header className="mb-7 flex items-center justify-between"><div><h1 className="text-4xl font-bold text-[#15383f]">错题本</h1><p className="mt-2 text-sm text-[#6c858a]">系统整理你的错题，循序渐进完成复习</p></div><button onClick={()=>router.push('/quiz')} className="rounded-full bg-[#07abd1] px-6 py-3 font-semibold text-white">添加错题</button></header><div className="mb-6 grid grid-cols-2 gap-4 xl:grid-cols-4"><Card label="累计错题" value={items.length}/><Card label="待复习" value={items.length}/><Card label="本周掌握率" value="78%"/><Card label="连续打卡" value="15天"/></div><div className="mb-4 flex flex-wrap gap-2">{tabs.map(x=><button key={x} onClick={()=>setTab(x)} className={`rounded-full px-5 py-2 text-sm font-semibold ${tab===x?'bg-[#07abd1] text-white':'bg-white'}`}>{x}</button>)}</div><section className="overflow-hidden rounded-2xl bg-white shadow-sm">{list.length===0?<div className="p-12 text-center text-[#6f858a]">暂无错题记录</div>:list.map((item,n)=>{const q=parse(item);return <article key={item.id} className="flex items-center gap-4 border-b p-5"><b className="rounded-full bg-[#32aeb5] px-3 py-2 text-white">{n+1}</b><div className="flex-1"><div className="font-semibold">{q.question}</div><small className="text-[#7b969a]">{category(item,q)} · 错误次数 1 · 薄弱</small></div><button onClick={()=>{setActive(item);setSelected(null);setSubmitted(false)}} className="rounded-full bg-[#07abd1] px-4 py-2 text-sm text-white">重新作答</button><button onClick={()=>addReview(item)} className="rounded-full border border-[#07abd1] px-4 py-2 text-sm text-[#078fbd]">加入复习</button></article>})}</section>{active&&<Review item={active} selected={selected} setSelected={setSelected} submitted={submitted} setSubmitted={setSubmitted} close={()=>setActive(null)}/>}</main>}
function Review({item,selected,setSelected,submitted,setSubmitted,close}:any){const q=parse(item);const opts=q.options||[];const answer=q.answer??q.correct_index??0;const ok=selected===answer;return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div className="w-full max-w-xl rounded-2xl bg-white p-6"><button onClick={close} className="float-right text-xl">×</button><h2 className="mb-5 text-xl font-bold">{q.question}</h2>{opts.map((o:any,i:number)=><button key={i} disabled={submitted} onClick={()=>setSelected(i)} className={`mb-2 w-full rounded-lg border p-3 text-left ${selected===i?'border-[#07abd1] bg-[#effcfc]':''}`}>{String.fromCharCode(65+i)}. {typeof o==='string'?o:o.text}</button>)}{opts.length>0&&<button disabled={selected===null||submitted} onClick={()=>setSubmitted(true)} className="mt-4 rounded-full bg-[#07abd1] px-5 py-2 text-white">提交答案</button>}{submitted&&<p className={ok?'text-green-600':'text-red-600'}>{ok?'回答正确':'回答错误'}：{q.explanation}</p>}</div></div>}
function Card({label,value}:{label:string;value:string|number}){return <div className="rounded-2xl bg-white p-5 shadow-sm"><div className="text-sm text-[#6f858a]">{label}</div><div className="mt-2 text-3xl font-bold text-[#253f46]">{value}</div></div>}
